---
title: "p8105_hw6_zq2209"
author: "Zining Qi"
date: "2022-11-30"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
```

# Problem 2
```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide = read_csv(url) %>% 
  janitor::clean_names()
```

```{r}
homicide$city_state = paste(homicide$city, homicide$state, sep = ', ')
homicide %>%
  head() %>% 
  knitr::kable()
```

```{r}
homicide_df = homicide %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL" ))) %>% 
  filter(victim_race %in% c("White", "Black"))
```

```{r}
homicide_df = homicide_df %>% 
  mutate(victim_age = ifelse(victim_age == "Unknown", NA, victim_age))
```

```{r}
homicide_df = homicide_df %>% 
  mutate(victim_age = strtoi(victim_age))
```


```{r}
homicide_data = homicide_df %>% 
  mutate(solved_or_not = ifelse(disposition == "Closed by arrest", 1, 0))
```

```{r}
glm_baltimore = homicide_data %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved_or_not ~ victim_sex + victim_race + victim_age, family = binomial, data = .)
```

```{r}
glm_baltimore_table = broom::tidy(glm_baltimore) %>% 
  mutate(or = exp(estimate), 
         or_lower = exp(estimate - 1.96*std.error), 
         or_upper = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(or, or_lower, or_upper) %>% 
  rename("Odds ratio" = or, 
         "Lower bound" = or_lower, 
         "Upper bound" = or_upper) %>% 
  knitr::kable(digits = 3)

glm_baltimore_table
```

```{r}
glm_all = function(citystate){
  city_glm = homicide_data %>% 
    filter(city_state == citystate) %>% 
    glm(solved_or_not ~ victim_sex + victim_race + victim_age, family = binomial, data = .) %>% 
    broom::tidy() %>% 
    mutate(or = exp(estimate), 
         or_lower = exp(estimate - 1.96*std.error), 
         or_upper = exp(estimate + 1.96*std.error)) %>% 
    filter(term == "victim_sexMale") %>% 
    select(or, or_lower, or_upper)
    
    city_glm
}
```

```{r}
city_state_list = homicide_data %>% 
  select(city_state) %>% 
  unique()
```

```{r}
glm_all_result = city_state_list %>% 
  mutate(glm_result = map(city_state, glm_all)) %>% 
  unnest(glm_result) %>% 
  arrange(desc(or))
```

```{r}
glm_all_table = glm_all_result %>% 
  rename("Odds ratio" = or, 
         "Lower bound" = or_lower, 
         "Upper bound" = or_upper) %>% 
  knitr::kable(digits = 3)

glm_all_table
```

```{r}
glm_all_result %>% 
  mutate(city_state = fct_reorder(city_state, or)) %>% 
  ggplot(aes(x = city_state, y = or)) + 
  geom_point(color = "red") + 
  geom_errorbar(aes(ymin = or_lower, ymax = or_upper)) + 
  coord_flip() + 
  labs(title = "Odds Ratio of solving cases comparing male victims to female victims", 
       y = "Odds ratio of solving cases", 
       x = "City, State", 
       caption = "Bars represent 95% confidence interval") + 
  theme_classic() 
```

## Problem 3

```{r}
birthweight = read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names()

birthweight = birthweight %>% 
  mutate(babysex = as.factor(babysex), 
         frace = as.factor(frace), 
         malform = as.factor(malform), 
         mrace = as.factor(mrace))
```


```{r}
birthweight_hist = birthweight %>% 
  ggplot(aes(x = bwt)) + 
  geom_histogram() + 
  labs(x = "Birthweight")
```

Length of Pregnancy
Mother's birth weight
Age of the parent
race
SES (income used as proxy here)

gaweeks
mrace
ppbmi
momage
fincome


```{r}
lm_bwt = lm(bwt ~ gaweeks+mrace+ppbmi+fincome+momage, data = birthweight)
```

```{r}
lm_bwt %>% broom::tidy()
```

```{r}
birthweight %>% 
  modelr::add_predictions(lm_bwt) %>% 
  modelr::add_residuals(lm_bwt) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm", color = "red") +
  labs(
    x = "Predicted Values",
    y = "Residuals",
    title = "Residuals vs. predicted values"
  )
```


```{r}
lm_main = lm(bwt ~ gaweeks+blength, data = birthweight)
lm_inter = lm(bwt ~ bhead*blength*babysex, data = birthweight)
```

```{r}
lm_main %>% broom::tidy()
lm_inter %>% broom::tidy()
```

```{r}
cv_df = 
  crossv_mc(birthweight, 100)
```

```{r}
cv_df = 
  cv_df %>% 
  mutate(
    lm_bwt  = map(train, ~lm(bwt ~ gaweeks+mrace+ppbmi+fincome+momage, data = .x)),
    lm_main  = map(train, ~lm(bwt ~ gaweeks+blength, data = .x)),
    lm_inter  = map(train, ~lm(bwt ~ bhead*blength*babysex, data = .x))) %>% 
  mutate(
    rmse_bwt = map2_dbl(lm_bwt, test, ~rmse(model = .x, data = .y)),
    rmse_main = map2_dbl(lm_main, test, ~rmse(model = .x, data = .y)),
    rmse_inter = map2_dbl(lm_inter, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin() +
  labs(
    x = "Model",
    y = "RMSE",
    title = "RMSE distribution across 3 models"
  )
```

The three-interaction model seems the best among three models.



